version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - echo Logged in complete...
      - REPOSITORY_URI=266112834201.dkr.ecr.eu-west-1.amazonaws.com/gigfrontend
      - IMAGE_TAG=latest
      - echo DockerBuild started on `date`
      - echo Building the Docker image... 
      - docker build -t gigfrontend .
      - ls -l   build
      - docker tag gigfrontend:latest $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
  install:
    commands:
      - printenv
  build:
    commands:
      - npm run prod
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - webpack.config.js
  discard-paths: yes
