version: 0.2

phases:

  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run prod
      - ls -lah public
      - ~/.local/bin/aws s3 cp public/* s3://clientsidetest/
artifacts:
  files:
    - public/**/*
    - package.json
