version: 0.2

phases:

  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - ls -lah /codebuild/output/src*/src/src/assets/js
      - npm run prod
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - webpack.config.js
  discard-paths: yes
