version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run prod
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - .eslintrc
    - webpack.config.js
    - jest.config.js
    - #.npmignore
	- .gitignore
	- .gitattributes
	- .eslintignore
	- .babelrc
  discard-paths: yes