version: 0.2

phases:

  install:
    commands:
      - printenv
  build:
    commands:
      - npm run prod
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - webpack.config.js
  discard-paths: yes
