version: 0.2

phases:

  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - ls -lah /codebuild/output/src*/src/src/assets/js
      - npm run prod
      - ls -lah public
artifacts:
  files:
    - public/**/*
    - package.json
