version: 0.2

phases:

  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run prod
      - ls -lah public
      - aws s3 cp dist s3://your_bucket/
artifacts:
  files:
    - public/**/*
    - package.json
