version: "2"
services:
    node:
        image: ${DOCKER_USER}/${DOCKER_IMAGE_NODE}:latest
        volumes:
            - ./:${APP_PATH}
        networks:
            - network
    nginx:
        image: ${DOCKER_USER}/${DOCKER_IMAGE_NGINX}:javascript
        volumes:
            - ./:${APP_PATH}
        networks:
            - network
        restart: always
    