version: "2"
services:
    node:
        extends: 
            file: docker-compose.base.yml
            service: node
    nginx:
        extends: 
            file: docker-compose.base.yml
            service: nginx
networks:
    network:
        driver: "bridge"
        