/**
 * @link https://www.giggrafter.com
 * @copyright Copyright (c) Gig Grafter
 * @license https://www.giggrafter.com/license
 */

export const FORM_STATUS = 'FORM_STATUS';
export const AJAX_LOADING = 'AJAX_LOADING';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const GET_USER_TYPES_SUCCESS = 'GET_USER_TYPES_SUCCESS';
export const GET_USER_TYPE_SUCCESS = 'GET_USER_TYPE_SUCCESS';
export const CREATE_USER_TYPE_SUCCESS = 'CREATE_USER_TYPE_SUCCESS';
export const UPDATE_USER_TYPE_SUCCESS = 'UPDATE_USER_TYPE_SUCCESS';
export const DELETE_USER_TYPE_SUCCESS = 'DELETE_USER_TYPE_SUCCESS';

export const GET_USER_ROLES_SUCCESS = 'GET_USER_ROLES_SUCCESS';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const CREATE_USER_ROLE_SUCCESS = 'CREATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_SUCCESS = 'DELETE_USER_ROLE_SUCCESS';

export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';

export const GET_SHIFTS_SUCCESS = 'GET_SHIFTS_SUCCESS';
export const GET_SHIFT_SUCCESS = 'GET_SHIFT_SUCCESS';
export const CREATE_SHIFT_SUCCESS = 'CREATE_SHIFT_SUCCESS';
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS';
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS';

export const GET_ROTAS_SUCCESS = 'GET_ROTAS_SUCCESS';
export const GET_ROTA_SUCCESS = 'GET_ROTA_SUCCESS';
export const CREATE_ROTA_SUCCESS = 'CREATE_ROTA_SUCCESS';
export const UPDATE_ROTA_SUCCESS = 'UPDATE_ROTA_SUCCESS';
export const DELETE_ROTA_SUCCESS = 'DELETE_ROTA_SUCCESS';

export const GET_ROTA_TYPES_SUCCESS = 'GET_ROTA_TYPES_SUCCESS';
export const GET_ROTA_TYPE_SUCCESS = 'GET_ROTA_TYPE_SUCCESS';
export const CREATE_ROTA_TYPE_SUCCESS = 'CREATE_ROTA_TYPE_SUCCESS';
export const UPDATE_ROTA_TYPE_SUCCESS = 'UPDATE_ROTA_TYPE_SUCCESS';
export const DELETE_ROTA_TYPE_SUCCESS = 'DELETE_ROTA_TYPE_SUCCESS';

export const GET_PLACEMENTS_SUCCESS = 'GET_PLACEMENTS_SUCCESS';
export const GET_PLACEMENT_SUCCESS = 'GET_PLACEMENT_SUCCESS';
export const CREATE_PLACEMENT_SUCCESS = 'CREATE_PLACEMENT_SUCCESS';
export const UPDATE_PLACEMENT_SUCCESS = 'UPDATE_PLACEMENT_SUCCESS';
export const DELETE_PLACEMENT_SUCCESS = 'DELETE_PLACEMENT_SUCCESS';
